version: "3.8"

services:
  db:
    image: mysql:8
    container_name: gitea_db
    environment:
      MYSQL_ROOT_PASSWORD: 34311622F
      MYSQL_DATABASE: gitea
      MYSQL_USER: gitea
      MYSQL_PASSWORD: gitea_password
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - gitea_network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-uroot",
          "-p34311622F",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea_password
    ports:
      - "3001:3000"
      - "222:22"
    volumes:
      - ./gitea_data:/data
    networks:
      - gitea_network

networks:
  gitea_network:
    driver: bridge
